scraper = "dummy.DummyScraper"
# scraper = "epaper.readwhere.tie.TIEScraperOCR"
keywords = ["suicide", "kill self", "ends life", "hang self", "found dead"]
ignore_keywords = ["suicide bomb"]
start = "2024-06-10"
end = "2024-06-11"
log_file = ".log"
# log_level
# max_concurrency = 1
# timeout = 1000
# cloud = true
# out = "data.csv"
