name: Test Hindustan Times Scraper

on: workflow_dispatch

jobs:
  scrape_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Install ChromeDriver
      run: |
        sudo apt update
        sudo apt install -y chromium-chromedriver
        echo "CHROMEDRIVER_PATH=$(which chromedriver)" >> $GITHUB_ENV

    - name: Run scraper
      env:
        SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.SERVICE_ACCOUNT_CREDENTIALS }}
        START: "01-07-2022"
        END: "01-10-2022"
      run: poetry run python run.py hindustan_times

    - name: Upload to Google Drive
      env:
        SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.SERVICE_ACCOUNT_CREDENTIALS }}
      run: |
        echo "$SERVICE_ACCOUNT_CREDENTIALS" > service_account.json  
        # python HindustanTimes/upload_drive.py  
